apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-wiki
  namespace: go-wiki
  labels:
    app: go-wiki
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-wiki
  template:
    metadata:
      labels:
        app: go-wiki
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /data"]
          volumeMounts:
            - name: wiki-data
              mountPath: /data
      containers:
        - name: go-wiki
          image: "krrishmahar/go-wiki:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: wiki-data
              mountPath: /data
      volumes:
        - name: wiki-data
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1